sudo: required
services:
  - docker

before_install:
  - docker build -t thephilgray/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true USERNAME/react-test npm test

after_success:
  - docker build -t thephilgray/multi-client ./client
  - docker build -t thephilgray/multi-nginx ./nginx
  - docker build -t thephilgray/multi-server ./server
  - docker build -t thephilgray/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take images and push them to dockerhub
  - docker push thephilgray/multi-client
  - docker push thephilgray/multi-nginx
  - docker push thephilgray/multi-server
  - docker push thephilgray/multi-worker
